// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EncryptedData.proto

package yotiprotocom_v3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedData struct {
	// the iv will be used in conjunction with the secret key
	// received via other channel in order to decrypt the cipher_text
	Iv []byte `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	// block of bytes to be decrypted
	CipherText           []byte   `protobuf:"bytes,2,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedData) Reset()         { *m = EncryptedData{} }
func (m *EncryptedData) String() string { return proto.CompactTextString(m) }
func (*EncryptedData) ProtoMessage()    {}
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_EncryptedData_dd7c465221750f20, []int{0}
}
func (m *EncryptedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedData.Unmarshal(m, b)
}
func (m *EncryptedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedData.Marshal(b, m, deterministic)
}
func (dst *EncryptedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedData.Merge(dst, src)
}
func (m *EncryptedData) XXX_Size() int {
	return xxx_messageInfo_EncryptedData.Size(m)
}
func (m *EncryptedData) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedData.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedData proto.InternalMessageInfo

func (m *EncryptedData) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *EncryptedData) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedData)(nil), "Yoti.Protobuf.compubapi_v3.EncryptedData")
}

func init() { proto.RegisterFile("EncryptedData.proto", fileDescriptor_EncryptedData_dd7c465221750f20) }

var fileDescriptor_EncryptedData_dd7c465221750f20 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x76, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x49, 0x4d, 0x71, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0x8a, 0xcc, 0x2f, 0xc9, 0xd4, 0x0b, 0x00, 0xb1, 0x93, 0x4a, 0xd3, 0xf4, 0x92, 0xf3, 0x73,
	0x0b, 0x4a, 0x93, 0x12, 0x0b, 0x32, 0xe3, 0xcb, 0x8c, 0x95, 0x1c, 0xb8, 0x78, 0x51, 0xb4, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0x96, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x31, 0x65, 0x96, 0x09,
	0xc9, 0x73, 0x71, 0x27, 0x67, 0x16, 0x64, 0xa4, 0x16, 0xc5, 0x97, 0xa4, 0x56, 0x94, 0x48, 0x30,
	0x81, 0x25, 0xb8, 0x20, 0x42, 0x21, 0xa9, 0x15, 0x25, 0x4e, 0x36, 0x5c, 0xa2, 0xc9, 0xf9, 0xb9,
	0x7a, 0x95, 0x20, 0x3b, 0x90, 0x8d, 0x76, 0x12, 0x42, 0x31, 0x18, 0x6c, 0x7d, 0x14, 0x3f, 0x48,
	0x19, 0xd8, 0x55, 0xc9, 0xf9, 0xb9, 0xf1, 0x65, 0xc6, 0x49, 0x6c, 0x60, 0x8e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x2a, 0xe3, 0xcb, 0xb9, 0x00, 0x00, 0x00,
}
