// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Attribute.proto

package yotiprotoattr_v3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ContentType indicates how to interpret the ‘Value’ field of an Attribute.
type ContentType int32

const (
	// UNDEFINED should not be seen, and is used as an error placeholder
	// value.
	ContentType_UNDEFINED ContentType = 0
	// STRING means the value is UTF-8 encoded text.
	ContentType_STRING ContentType = 1
	// JPEG indicates a standard .jpeg image.
	ContentType_JPEG ContentType = 2
	// Date as string in RFC3339 format (YYYY-MM-DD).
	ContentType_DATE ContentType = 3
	// PNG indicates a standard .png image.
	ContentType_PNG ContentType = 4
	// JSON means the value is encoded using JSON.
	ContentType_JSON ContentType = 5
)

var ContentType_name = map[int32]string{
	0: "UNDEFINED",
	1: "STRING",
	2: "JPEG",
	3: "DATE",
	4: "PNG",
	5: "JSON",
}
var ContentType_value = map[string]int32{
	"UNDEFINED": 0,
	"STRING":    1,
	"JPEG":      2,
	"DATE":      3,
	"PNG":       4,
	"JSON":      5,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Attribute_b982115ef766f90a, []int{0}
}

type Attribute struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ContentType          ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,enum=Yoti.Protobuf.attrpubapi_v3.ContentType" json:"content_type,omitempty"`
	Anchors              []*Anchor   `protobuf:"bytes,4,rep,name=anchors" json:"anchors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_Attribute_b982115ef766f90a, []int{0}
}
func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (dst *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(dst, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Attribute) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_UNDEFINED
}

func (m *Attribute) GetAnchors() []*Anchor {
	if m != nil {
		return m.Anchors
	}
	return nil
}

type Anchor struct {
	ArtifactLink         []byte   `protobuf:"bytes,1,opt,name=artifact_link,json=artifactLink,proto3" json:"artifact_link,omitempty"`
	OriginServerCerts    [][]byte `protobuf:"bytes,2,rep,name=origin_server_certs,json=originServerCerts,proto3" json:"origin_server_certs,omitempty"`
	ArtifactSignature    []byte   `protobuf:"bytes,3,opt,name=artifact_signature,json=artifactSignature,proto3" json:"artifact_signature,omitempty"`
	SubType              string   `protobuf:"bytes,4,opt,name=sub_type,json=subType" json:"sub_type,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	SignedTimeStamp      []byte   `protobuf:"bytes,6,opt,name=signed_time_stamp,json=signedTimeStamp,proto3" json:"signed_time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anchor) Reset()         { *m = Anchor{} }
func (m *Anchor) String() string { return proto.CompactTextString(m) }
func (*Anchor) ProtoMessage()    {}
func (*Anchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_Attribute_b982115ef766f90a, []int{1}
}
func (m *Anchor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anchor.Unmarshal(m, b)
}
func (m *Anchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anchor.Marshal(b, m, deterministic)
}
func (dst *Anchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anchor.Merge(dst, src)
}
func (m *Anchor) XXX_Size() int {
	return xxx_messageInfo_Anchor.Size(m)
}
func (m *Anchor) XXX_DiscardUnknown() {
	xxx_messageInfo_Anchor.DiscardUnknown(m)
}

var xxx_messageInfo_Anchor proto.InternalMessageInfo

func (m *Anchor) GetArtifactLink() []byte {
	if m != nil {
		return m.ArtifactLink
	}
	return nil
}

func (m *Anchor) GetOriginServerCerts() [][]byte {
	if m != nil {
		return m.OriginServerCerts
	}
	return nil
}

func (m *Anchor) GetArtifactSignature() []byte {
	if m != nil {
		return m.ArtifactSignature
	}
	return nil
}

func (m *Anchor) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Anchor) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Anchor) GetSignedTimeStamp() []byte {
	if m != nil {
		return m.SignedTimeStamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Attribute)(nil), "Yoti.Protobuf.attrpubapi_v3.Attribute")
	proto.RegisterType((*Anchor)(nil), "Yoti.Protobuf.attrpubapi_v3.Anchor")
	proto.RegisterEnum("Yoti.Protobuf.attrpubapi_v3.ContentType", ContentType_name, ContentType_value)
}

func init() { proto.RegisterFile("Attribute.proto", fileDescriptor_Attribute_b982115ef766f90a) }

var fileDescriptor_Attribute_b982115ef766f90a = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0xec, 0x24, 0xcd, 0xc4, 0xa5, 0xce, 0x80, 0x90, 0x11, 0x1c, 0xac, 0xf6, 0x62,
	0x55, 0xc2, 0x87, 0x46, 0x1c, 0x39, 0xa4, 0x4d, 0x88, 0x0a, 0xc8, 0x8d, 0xec, 0x70, 0x80, 0x8b,
	0xb5, 0x36, 0xdb, 0xb2, 0x6a, 0xbd, 0xb6, 0xd6, 0xe3, 0x48, 0x79, 0x3c, 0x1e, 0x89, 0x37, 0x40,
	0xbb, 0x96, 0x1b, 0x7a, 0xe9, 0x6d, 0xe6, 0xff, 0x66, 0x7e, 0x6b, 0x7e, 0x2f, 0x9c, 0x2c, 0x88,
	0x94, 0xc8, 0x5b, 0xe2, 0x51, 0xad, 0x2a, 0xaa, 0xf0, 0xdd, 0x8f, 0x8a, 0x44, 0xb4, 0xd1, 0x75,
	0xde, 0xde, 0x46, 0x8c, 0x48, 0xd5, 0x6d, 0xce, 0x6a, 0x91, 0xed, 0xe6, 0xa7, 0x7f, 0x2c, 0x98,
	0x3c, 0x2e, 0x20, 0x82, 0x23, 0x59, 0xc9, 0x7d, 0x2b, 0xb0, 0xc2, 0x49, 0x62, 0x6a, 0x7c, 0x0d,
	0xc3, 0x1d, 0x7b, 0x68, 0xb9, 0x3f, 0x08, 0xac, 0xd0, 0x4d, 0xba, 0x06, 0xbf, 0x82, 0x5b, 0x54,
	0x92, 0xb8, 0xa4, 0x8c, 0xf6, 0x35, 0xf7, 0xed, 0xc0, 0x0a, 0x5f, 0x5e, 0x84, 0xd1, 0x33, 0xdf,
	0x8a, 0xae, 0xba, 0x85, 0xed, 0xbe, 0xe6, 0xc9, 0xb4, 0x38, 0x34, 0xf8, 0x09, 0xc6, 0x4c, 0x16,
	0xbf, 0x2b, 0xd5, 0xf8, 0x4e, 0x60, 0x87, 0xd3, 0x8b, 0xb3, 0x67, 0x7d, 0x16, 0x66, 0x36, 0xe9,
	0x77, 0x4e, 0xff, 0x5a, 0x30, 0xea, 0x34, 0x3c, 0x83, 0x63, 0xa6, 0x48, 0xdc, 0xb2, 0x82, 0xb2,
	0x07, 0x21, 0xef, 0xcd, 0x25, 0x6e, 0xe2, 0xf6, 0xe2, 0x37, 0x21, 0xef, 0x31, 0x82, 0x57, 0x95,
	0x12, 0x77, 0x42, 0x66, 0x0d, 0x57, 0x3b, 0xae, 0xb2, 0x82, 0x2b, 0x6a, 0xfc, 0x41, 0x60, 0x87,
	0x6e, 0x32, 0xeb, 0x50, 0x6a, 0xc8, 0x95, 0x06, 0xf8, 0x01, 0xf0, 0xd1, 0xb4, 0x11, 0x77, 0x92,
	0x51, 0xab, 0xba, 0x8b, 0xdd, 0x64, 0xd6, 0x93, 0xb4, 0x07, 0xf8, 0x16, 0x8e, 0x9a, 0x36, 0xef,
	0x62, 0x71, 0x4c, 0x90, 0xe3, 0xa6, 0xcd, 0xcd, 0xa1, 0xef, 0x61, 0x72, 0x30, 0x18, 0x1a, 0x83,
	0x83, 0x80, 0xe7, 0x30, 0xd3, 0x0d, 0xff, 0x95, 0x91, 0x28, 0x79, 0xd6, 0x10, 0x2b, 0x6b, 0x7f,
	0x64, 0xa6, 0x4e, 0x3a, 0xb0, 0x15, 0x25, 0x4f, 0xb5, 0x7c, 0x7e, 0x03, 0xd3, 0xff, 0xe2, 0xc4,
	0x63, 0x98, 0x7c, 0x8f, 0x97, 0xab, 0xcf, 0xd7, 0xf1, 0x6a, 0xe9, 0xbd, 0x40, 0x80, 0x51, 0xba,
	0x4d, 0xae, 0xe3, 0xb5, 0x67, 0xe1, 0x11, 0x38, 0x5f, 0x36, 0xab, 0xb5, 0x37, 0xd0, 0xd5, 0x72,
	0xb1, 0x5d, 0x79, 0x36, 0x8e, 0xc1, 0xde, 0xc4, 0x6b, 0xcf, 0x31, 0x30, 0xbd, 0x89, 0xbd, 0xe1,
	0xe5, 0x47, 0x78, 0x53, 0x54, 0x65, 0xb4, 0xd7, 0xb9, 0x3f, 0x89, 0xfb, 0xd2, 0xbc, 0x0f, 0xf3,
	0x2b, 0x7e, 0x7a, 0x1a, 0x9b, 0x57, 0xa5, 0x47, 0xb2, 0xdd, 0x3c, 0x1f, 0x99, 0x6e, 0xfe, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x9f, 0xa7, 0xb7, 0x76, 0x02, 0x00, 0x00,
}
