// Code generated by protoc-gen-go. DO NOT EDIT.
// source: List.proto

package yotiprotoattr_v3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AttributeAndId is a simple container for holding an attribute's value
// alongside its ID.
type AttributeAndId struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute" json:"attribute,omitempty"`
	AttributeId          []byte     `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AttributeAndId) Reset()         { *m = AttributeAndId{} }
func (m *AttributeAndId) String() string { return proto.CompactTextString(m) }
func (*AttributeAndId) ProtoMessage()    {}
func (*AttributeAndId) Descriptor() ([]byte, []int) {
	return fileDescriptor_List_e372555a05843a88, []int{0}
}
func (m *AttributeAndId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeAndId.Unmarshal(m, b)
}
func (m *AttributeAndId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeAndId.Marshal(b, m, deterministic)
}
func (dst *AttributeAndId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeAndId.Merge(dst, src)
}
func (m *AttributeAndId) XXX_Size() int {
	return xxx_messageInfo_AttributeAndId.Size(m)
}
func (m *AttributeAndId) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeAndId.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeAndId proto.InternalMessageInfo

func (m *AttributeAndId) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *AttributeAndId) GetAttributeId() []byte {
	if m != nil {
		return m.AttributeId
	}
	return nil
}

type AttributeAndIdList struct {
	AttributeAndIdList   []*AttributeAndId `protobuf:"bytes,1,rep,name=attribute_and_id_list,json=attributeAndIdList" json:"attribute_and_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AttributeAndIdList) Reset()         { *m = AttributeAndIdList{} }
func (m *AttributeAndIdList) String() string { return proto.CompactTextString(m) }
func (*AttributeAndIdList) ProtoMessage()    {}
func (*AttributeAndIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_List_e372555a05843a88, []int{1}
}
func (m *AttributeAndIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeAndIdList.Unmarshal(m, b)
}
func (m *AttributeAndIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeAndIdList.Marshal(b, m, deterministic)
}
func (dst *AttributeAndIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeAndIdList.Merge(dst, src)
}
func (m *AttributeAndIdList) XXX_Size() int {
	return xxx_messageInfo_AttributeAndIdList.Size(m)
}
func (m *AttributeAndIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeAndIdList.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeAndIdList proto.InternalMessageInfo

func (m *AttributeAndIdList) GetAttributeAndIdList() []*AttributeAndId {
	if m != nil {
		return m.AttributeAndIdList
	}
	return nil
}

type AttributeList struct {
	Attributes           []*Attribute `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AttributeList) Reset()         { *m = AttributeList{} }
func (m *AttributeList) String() string { return proto.CompactTextString(m) }
func (*AttributeList) ProtoMessage()    {}
func (*AttributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_List_e372555a05843a88, []int{2}
}
func (m *AttributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeList.Unmarshal(m, b)
}
func (m *AttributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeList.Marshal(b, m, deterministic)
}
func (dst *AttributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeList.Merge(dst, src)
}
func (m *AttributeList) XXX_Size() int {
	return xxx_messageInfo_AttributeList.Size(m)
}
func (m *AttributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeList.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeList proto.InternalMessageInfo

func (m *AttributeList) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*AttributeAndId)(nil), "Yoti.Protobuf.attrpubapi_v3.AttributeAndId")
	proto.RegisterType((*AttributeAndIdList)(nil), "Yoti.Protobuf.attrpubapi_v3.AttributeAndIdList")
	proto.RegisterType((*AttributeList)(nil), "Yoti.Protobuf.attrpubapi_v3.AttributeList")
}

func init() { proto.RegisterFile("List.proto", fileDescriptor_List_e372555a05843a88) }

var fileDescriptor_List_e372555a05843a88 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf2, 0xc9, 0x2c, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x8e, 0xcc, 0x2f, 0xc9, 0xd4, 0x0b, 0x00, 0xb1,
	0x93, 0x4a, 0xd3, 0xf4, 0x12, 0x4b, 0x4a, 0x8a, 0x0a, 0x4a, 0x93, 0x12, 0x0b, 0x32, 0xe3, 0xcb,
	0x8c, 0xa5, 0xf8, 0x1d, 0x4b, 0x4a, 0x8a, 0x32, 0x93, 0x4a, 0x4b, 0x52, 0x21, 0xaa, 0x95, 0x2a,
	0xb9, 0xf8, 0xe0, 0x42, 0x8e, 0x79, 0x29, 0x9e, 0x29, 0x42, 0x2e, 0x5c, 0x9c, 0x89, 0x30, 0x11,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x35, 0x3d, 0x3c, 0x66, 0xea, 0xc1, 0xf5, 0x07, 0x21,
	0x34, 0x0a, 0x29, 0x72, 0xf1, 0xc0, 0x39, 0xf1, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c,
	0x41, 0xdc, 0x70, 0x31, 0xcf, 0x14, 0xa5, 0x12, 0x2e, 0x21, 0x54, 0xab, 0x41, 0x9e, 0x10, 0x8a,
	0xe3, 0x12, 0x45, 0x68, 0x4c, 0xcc, 0x4b, 0x89, 0xcf, 0x4c, 0x89, 0xcf, 0xc9, 0x2c, 0x2e, 0x91,
	0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xd2, 0x26, 0xce, 0x29, 0x60, 0xf3, 0x82, 0x84, 0x12, 0x31,
	0xcc, 0x57, 0x0a, 0xe7, 0xe2, 0x85, 0xab, 0x02, 0x5b, 0xe8, 0xc6, 0xc5, 0x05, 0x57, 0x56, 0x0c,
	0xb5, 0x85, 0x58, 0x0f, 0x23, 0xe9, 0x74, 0x32, 0xe5, 0x12, 0x4b, 0xce, 0xcf, 0xd5, 0xab, 0x04,
	0x69, 0x44, 0x51, 0xef, 0xc4, 0x09, 0xd2, 0x00, 0x36, 0x2b, 0x4a, 0x00, 0x24, 0x0d, 0x0e, 0x79,
	0x90, 0x92, 0xf8, 0x32, 0xe3, 0x24, 0x36, 0x30, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x56,
	0xdb, 0xb5, 0x1d, 0xc3, 0x01, 0x00, 0x00,
}
