// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IssuingAttributes.proto

package yotiprotoshare

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IssuingAttributes struct {
	ExpiryDate           string        `protobuf:"bytes,1,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	Definitions          []*Definition `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IssuingAttributes) Reset()         { *m = IssuingAttributes{} }
func (m *IssuingAttributes) String() string { return proto.CompactTextString(m) }
func (*IssuingAttributes) ProtoMessage()    {}
func (*IssuingAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2dd0b18c44f072, []int{0}
}

func (m *IssuingAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuingAttributes.Unmarshal(m, b)
}
func (m *IssuingAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuingAttributes.Marshal(b, m, deterministic)
}
func (m *IssuingAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuingAttributes.Merge(m, src)
}
func (m *IssuingAttributes) XXX_Size() int {
	return xxx_messageInfo_IssuingAttributes.Size(m)
}
func (m *IssuingAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuingAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_IssuingAttributes proto.InternalMessageInfo

func (m *IssuingAttributes) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *IssuingAttributes) GetDefinitions() []*Definition {
	if m != nil {
		return m.Definitions
	}
	return nil
}

type Definition struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Definition) Reset()         { *m = Definition{} }
func (m *Definition) String() string { return proto.CompactTextString(m) }
func (*Definition) ProtoMessage()    {}
func (*Definition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2dd0b18c44f072, []int{1}
}

func (m *Definition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Definition.Unmarshal(m, b)
}
func (m *Definition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Definition.Marshal(b, m, deterministic)
}
func (m *Definition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Definition.Merge(m, src)
}
func (m *Definition) XXX_Size() int {
	return xxx_messageInfo_Definition.Size(m)
}
func (m *Definition) XXX_DiscardUnknown() {
	xxx_messageInfo_Definition.DiscardUnknown(m)
}

var xxx_messageInfo_Definition proto.InternalMessageInfo

func (m *Definition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*IssuingAttributes)(nil), "sharepubapi_v1.IssuingAttributes")
	proto.RegisterType((*Definition)(nil), "sharepubapi_v1.Definition")
}

func init() { proto.RegisterFile("IssuingAttributes.proto", fileDescriptor_8d2dd0b18c44f072) }

var fileDescriptor_8d2dd0b18c44f072 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x69, 0x14, 0xc1, 0x09, 0x14, 0xcd, 0x42, 0xa3, 0x08, 0x86, 0xe2, 0xa2, 0xab, 0x07,
	0xea, 0xd6, 0x4d, 0x43, 0x41, 0x5c, 0x08, 0xa5, 0x5d, 0x29, 0x85, 0x32, 0x69, 0x5e, 0xed, 0x03,
	0x33, 0x33, 0xcc, 0xbc, 0x11, 0x7b, 0x25, 0x2f, 0xe0, 0x1d, 0x3c, 0x86, 0x4b, 0x4f, 0x21, 0x33,
	0xa1, 0x56, 0xed, 0x2e, 0xfc, 0xff, 0x97, 0xef, 0xfd, 0x23, 0x8e, 0xef, 0x9c, 0xf3, 0xa4, 0x9e,
	0x06, 0xcc, 0x96, 0x2a, 0xcf, 0xe8, 0xc0, 0x58, 0xcd, 0x3a, 0xeb, 0xba, 0xa5, 0xb4, 0x68, 0x7c,
	0x25, 0x0d, 0xcd, 0x5e, 0x2e, 0x7b, 0x56, 0x1c, 0x6e, 0xa1, 0xd9, 0xb9, 0x48, 0xf1, 0xd5, 0x90,
	0x5d, 0xcd, 0x6a, 0xc9, 0x98, 0x77, 0x8a, 0x4e, 0x7f, 0x7f, 0x2c, 0xda, 0x68, 0x28, 0x19, 0xb3,
	0x1b, 0x91, 0xd6, 0xb8, 0x20, 0x45, 0x4c, 0x5a, 0xb9, 0x3c, 0x29, 0x76, 0xfa, 0xe9, 0xd5, 0x29,
	0xfc, 0x75, 0xc3, 0xf0, 0x07, 0x19, 0xff, 0xc6, 0x7b, 0x85, 0x10, 0x9b, 0x2a, 0xcb, 0xc4, 0xae,
	0x92, 0xcd, 0xfa, 0x4a, 0xfc, 0x2e, 0xdf, 0x3b, 0xe2, 0x62, 0xae, 0x1b, 0x58, 0x69, 0x26, 0x90,
	0x86, 0x60, 0xfe, 0x4c, 0xa8, 0x18, 0x9c, 0x21, 0xb0, 0xd8, 0x68, 0xc6, 0xf6, 0x39, 0xe5, 0xd1,
	0xd6, 0xf8, 0x51, 0xc8, 0x1f, 0xbb, 0xe1, 0xcf, 0x88, 0xc4, 0x4d, 0x6f, 0x49, 0xfe, 0x10, 0x54,
	0x03, 0xcf, 0x4b, 0x88, 0x44, 0xe9, 0x17, 0x30, 0x09, 0xd5, 0x47, 0x72, 0x10, 0xaa, 0xe9, 0x64,
	0xb3, 0xfd, 0x33, 0x39, 0xfb, 0x1f, 0x4d, 0x6f, 0x47, 0xe5, 0x3d, 0xb2, 0xac, 0x25, 0xcb, 0xaf,
	0xe4, 0x24, 0xca, 0xa2, 0xa7, 0x5a, 0x7b, 0x5a, 0xae, 0xda, 0x8b, 0x47, 0xaf, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xb4, 0x29, 0xb9, 0xd6, 0x81, 0x01, 0x00, 0x00,
}
