package retrieve

// GeneratedCheckResponse represents a check response that has been generated by the session
type GeneratedCheckResponse struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// GeneratedTextDataCheckResponse represents a Text Extraction task response
type GeneratedTextDataCheckResponse struct {
	*GeneratedCheckResponse
}
