package retrieve

// GeneratedCheckResponse represents a check response that has been generated by the session
type GeneratedCheckResponse struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// GeneratedTextDataCheckResponse represents a text data check response
type GeneratedTextDataCheckResponse struct {
	*GeneratedCheckResponse
}

// GeneratedSupplementaryTextDataCheckResponse represents a supplementary text data check response
type GeneratedSupplementaryTextDataCheckResponse struct {
	*GeneratedCheckResponse
}
