// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EncryptedData.proto

package yotiprotocom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedData struct {
	// the iv will be used in conjunction with the secret key
	// received via other channel in order to decrypt the cipher_text
	Iv []byte `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	// block of bytes to be decrypted
	CipherText           []byte   `protobuf:"bytes,2,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedData) Reset()         { *m = EncryptedData{} }
func (m *EncryptedData) String() string { return proto.CompactTextString(m) }
func (*EncryptedData) ProtoMessage()    {}
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed1db0e32f8afa88, []int{0}
}

func (m *EncryptedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedData.Unmarshal(m, b)
}
func (m *EncryptedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedData.Marshal(b, m, deterministic)
}
func (m *EncryptedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedData.Merge(m, src)
}
func (m *EncryptedData) XXX_Size() int {
	return xxx_messageInfo_EncryptedData.Size(m)
}
func (m *EncryptedData) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedData.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedData proto.InternalMessageInfo

func (m *EncryptedData) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *EncryptedData) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedData)(nil), "compubapi_v1.EncryptedData")
}

func init() { proto.RegisterFile("EncryptedData.proto", fileDescriptor_ed1db0e32f8afa88) }

var fileDescriptor_ed1db0e32f8afa88 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x76, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x49, 0x4d, 0x71, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x49, 0xce, 0xcf, 0x2d, 0x28, 0x4d, 0x4a, 0x2c, 0xc8, 0x8c, 0x2f, 0x33, 0x54, 0x72, 0xe0,
	0xe2, 0x45, 0x51, 0x24, 0xc4, 0xc7, 0xc5, 0x94, 0x59, 0x26, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13,
	0xc4, 0x94, 0x59, 0x26, 0x24, 0xcf, 0xc5, 0x9d, 0x9c, 0x59, 0x90, 0x91, 0x5a, 0x14, 0x5f, 0x92,
	0x5a, 0x51, 0x22, 0xc1, 0x04, 0x96, 0xe0, 0x82, 0x08, 0x85, 0xa4, 0x56, 0x94, 0x38, 0x59, 0x72,
	0x89, 0x26, 0xe7, 0xe7, 0xea, 0x55, 0xe6, 0x97, 0x64, 0xea, 0x21, 0x19, 0x6d, 0xec, 0x24, 0x84,
	0x62, 0x70, 0x00, 0xc8, 0xf2, 0x28, 0x1e, 0x90, 0x32, 0xb0, 0x3b, 0x92, 0xf3, 0x73, 0x93, 0xd8,
	0xc0, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xe9, 0x2c, 0x57, 0xa8, 0x00, 0x00,
	0x00,
}
