// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Attribute.proto

package yotiprotoattr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Attribute struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ContentType          ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=attrpubapi_v1.ContentType" json:"content_type,omitempty"`
	Anchors              []*Anchor   `protobuf:"bytes,4,rep,name=anchors,proto3" json:"anchors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d6ebe2a990cc1d, []int{0}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Attribute) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_UNDEFINED
}

func (m *Attribute) GetAnchors() []*Anchor {
	if m != nil {
		return m.Anchors
	}
	return nil
}

type Anchor struct {
	ArtifactLink         []byte   `protobuf:"bytes,1,opt,name=artifact_link,json=artifactLink,proto3" json:"artifact_link,omitempty"`
	OriginServerCerts    [][]byte `protobuf:"bytes,2,rep,name=origin_server_certs,json=originServerCerts,proto3" json:"origin_server_certs,omitempty"`
	ArtifactSignature    []byte   `protobuf:"bytes,3,opt,name=artifact_signature,json=artifactSignature,proto3" json:"artifact_signature,omitempty"`
	SubType              string   `protobuf:"bytes,4,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	SignedTimeStamp      []byte   `protobuf:"bytes,6,opt,name=signed_time_stamp,json=signedTimeStamp,proto3" json:"signed_time_stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anchor) Reset()         { *m = Anchor{} }
func (m *Anchor) String() string { return proto.CompactTextString(m) }
func (*Anchor) ProtoMessage()    {}
func (*Anchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d6ebe2a990cc1d, []int{1}
}

func (m *Anchor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anchor.Unmarshal(m, b)
}
func (m *Anchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anchor.Marshal(b, m, deterministic)
}
func (m *Anchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anchor.Merge(m, src)
}
func (m *Anchor) XXX_Size() int {
	return xxx_messageInfo_Anchor.Size(m)
}
func (m *Anchor) XXX_DiscardUnknown() {
	xxx_messageInfo_Anchor.DiscardUnknown(m)
}

var xxx_messageInfo_Anchor proto.InternalMessageInfo

func (m *Anchor) GetArtifactLink() []byte {
	if m != nil {
		return m.ArtifactLink
	}
	return nil
}

func (m *Anchor) GetOriginServerCerts() [][]byte {
	if m != nil {
		return m.OriginServerCerts
	}
	return nil
}

func (m *Anchor) GetArtifactSignature() []byte {
	if m != nil {
		return m.ArtifactSignature
	}
	return nil
}

func (m *Anchor) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Anchor) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Anchor) GetSignedTimeStamp() []byte {
	if m != nil {
		return m.SignedTimeStamp
	}
	return nil
}

type MultiValue struct {
	Values               []*MultiValue_Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MultiValue) Reset()         { *m = MultiValue{} }
func (m *MultiValue) String() string { return proto.CompactTextString(m) }
func (*MultiValue) ProtoMessage()    {}
func (*MultiValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d6ebe2a990cc1d, []int{2}
}

func (m *MultiValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiValue.Unmarshal(m, b)
}
func (m *MultiValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiValue.Marshal(b, m, deterministic)
}
func (m *MultiValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiValue.Merge(m, src)
}
func (m *MultiValue) XXX_Size() int {
	return xxx_messageInfo_MultiValue.Size(m)
}
func (m *MultiValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiValue.DiscardUnknown(m)
}

var xxx_messageInfo_MultiValue proto.InternalMessageInfo

func (m *MultiValue) GetValues() []*MultiValue_Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type MultiValue_Value struct {
	ContentType          ContentType `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3,enum=attrpubapi_v1.ContentType" json:"content_type,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MultiValue_Value) Reset()         { *m = MultiValue_Value{} }
func (m *MultiValue_Value) String() string { return proto.CompactTextString(m) }
func (*MultiValue_Value) ProtoMessage()    {}
func (*MultiValue_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d6ebe2a990cc1d, []int{2, 0}
}

func (m *MultiValue_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiValue_Value.Unmarshal(m, b)
}
func (m *MultiValue_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiValue_Value.Marshal(b, m, deterministic)
}
func (m *MultiValue_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiValue_Value.Merge(m, src)
}
func (m *MultiValue_Value) XXX_Size() int {
	return xxx_messageInfo_MultiValue_Value.Size(m)
}
func (m *MultiValue_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiValue_Value.DiscardUnknown(m)
}

var xxx_messageInfo_MultiValue_Value proto.InternalMessageInfo

func (m *MultiValue_Value) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_UNDEFINED
}

func (m *MultiValue_Value) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Attribute)(nil), "attrpubapi_v1.Attribute")
	proto.RegisterType((*Anchor)(nil), "attrpubapi_v1.Anchor")
	proto.RegisterType((*MultiValue)(nil), "attrpubapi_v1.MultiValue")
	proto.RegisterType((*MultiValue_Value)(nil), "attrpubapi_v1.MultiValue.Value")
}

func init() { proto.RegisterFile("Attribute.proto", fileDescriptor_44d6ebe2a990cc1d) }

var fileDescriptor_44d6ebe2a990cc1d = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xd6, 0xe6, 0xaf, 0x64, 0xea, 0x50, 0x65, 0x01, 0xc9, 0x44, 0x95, 0xb0, 0x02, 0x07, 0x0b,
	0x89, 0x45, 0x94, 0x03, 0x27, 0x0e, 0x49, 0xaf, 0x20, 0x21, 0xa7, 0xaa, 0x44, 0x2f, 0xd6, 0xda,
	0xdd, 0xb6, 0xab, 0xda, 0x6b, 0x6b, 0x77, 0x36, 0x52, 0x1e, 0x87, 0x03, 0x17, 0x1e, 0x85, 0xb7,
	0xe1, 0x0d, 0x90, 0xc7, 0x71, 0x0c, 0x15, 0x17, 0x2e, 0xd6, 0xcc, 0xf7, 0x7d, 0x33, 0xe3, 0xf9,
	0x76, 0xe0, 0x64, 0x85, 0x68, 0x75, 0xe6, 0x51, 0x89, 0xda, 0x56, 0x58, 0xf1, 0x99, 0x44, 0xb4,
	0xb5, 0xcf, 0x64, 0xad, 0xd3, 0xed, 0xbb, 0xc5, 0xfc, 0xbc, 0x32, 0xa8, 0x0c, 0x5e, 0xec, 0xea,
	0xbd, 0x62, 0xf9, 0x9d, 0xc1, 0xf4, 0x50, 0xc5, 0x39, 0x8c, 0x8c, 0x2c, 0x55, 0xc8, 0x22, 0x16,
	0x4f, 0x13, 0x8a, 0xf9, 0x53, 0x18, 0x6f, 0x65, 0xe1, 0x55, 0x38, 0x88, 0x58, 0x1c, 0x24, 0x6d,
	0xc2, 0x3f, 0x42, 0x90, 0xb7, 0xcd, 0x52, 0xdc, 0xd5, 0x2a, 0x1c, 0x46, 0x2c, 0x7e, 0x7c, 0xb6,
	0x10, 0x7f, 0x0d, 0x14, 0x7f, 0xcc, 0x4b, 0x8e, 0xf3, 0x3e, 0xe1, 0x6f, 0xe1, 0x48, 0x9a, 0xfc,
	0xae, 0xb2, 0x2e, 0x1c, 0x45, 0xc3, 0xf8, 0xf8, 0xec, 0xd9, 0x83, 0xca, 0x15, 0xb1, 0x49, 0xa7,
	0x5a, 0xfe, 0x62, 0x30, 0x69, 0x31, 0xfe, 0x12, 0x66, 0xd2, 0xa2, 0xbe, 0x91, 0x39, 0xa6, 0x85,
	0x36, 0xf7, 0xf4, 0xb7, 0x41, 0x12, 0x74, 0xe0, 0x27, 0x6d, 0xee, 0xb9, 0x80, 0x27, 0x95, 0xd5,
	0xb7, 0xda, 0xa4, 0x4e, 0xd9, 0xad, 0xb2, 0x69, 0xae, 0x2c, 0xba, 0x70, 0x10, 0x0d, 0xe3, 0x20,
	0x99, 0xb7, 0xd4, 0x86, 0x98, 0xf3, 0x86, 0xe0, 0x6f, 0x80, 0x1f, 0x9a, 0x3a, 0x7d, 0x6b, 0x24,
	0x7a, 0xdb, 0x6e, 0x15, 0x24, 0xf3, 0x8e, 0xd9, 0x74, 0x04, 0x7f, 0x0e, 0x8f, 0x9c, 0xcf, 0xda,
	0xd5, 0x47, 0x64, 0xd6, 0x91, 0xf3, 0x19, 0xad, 0x76, 0x0a, 0xd3, 0xbe, 0xc1, 0x98, 0x1a, 0xf4,
	0x00, 0x7f, 0x0d, 0xf3, 0x26, 0x51, 0xd7, 0x29, 0xea, 0x52, 0xa5, 0x0e, 0x65, 0x59, 0x87, 0x13,
	0x52, 0x9d, 0xb4, 0xc4, 0x85, 0x2e, 0xd5, 0xa6, 0x81, 0x97, 0xdf, 0x18, 0xc0, 0x67, 0x5f, 0xa0,
	0xbe, 0x24, 0xcb, 0x3f, 0xc0, 0x84, 0xbc, 0x77, 0x21, 0x23, 0xcb, 0x5e, 0x3c, 0xb0, 0xac, 0x97,
	0x0a, 0xfa, 0x26, 0x7b, 0xf9, 0xe2, 0x0a, 0xc6, 0x97, 0xff, 0x7c, 0x34, 0xf6, 0x7f, 0x8f, 0xc6,
	0x61, 0x74, 0x2d, 0x51, 0xee, 0x0f, 0x81, 0xe2, 0x75, 0x01, 0xaf, 0xf2, 0xaa, 0x14, 0xbb, 0x0a,
	0xb5, 0x90, 0xb5, 0x16, 0x79, 0xa1, 0x95, 0x41, 0xe1, 0x6a, 0x2d, 0xac, 0x2a, 0xab, 0xee, 0x12,
	0xd7, 0x74, 0x64, 0x5f, 0x9a, 0xf0, 0x6a, 0xd6, 0x88, 0x09, 0x6d, 0xe6, 0xfe, 0x18, 0x9c, 0x7e,
	0x6d, 0x8a, 0x57, 0x1e, 0xef, 0x04, 0x09, 0xd6, 0xfe, 0x46, 0x1c, 0x4e, 0xf2, 0xe7, 0x00, 0x56,
	0x87, 0xbf, 0xcb, 0x26, 0x54, 0xf6, 0xfe, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x08, 0x8c,
	0x4b, 0xe9, 0x02, 0x00, 0x00,
}
