// Code generated by protoc-gen-go. DO NOT EDIT.
// source: List.proto

package yotiprotoattr

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AttributeAndId struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	AttributeId          []byte     `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AttributeAndId) Reset()         { *m = AttributeAndId{} }
func (m *AttributeAndId) String() string { return proto.CompactTextString(m) }
func (*AttributeAndId) ProtoMessage()    {}
func (*AttributeAndId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23ec92774814a82, []int{0}
}

func (m *AttributeAndId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeAndId.Unmarshal(m, b)
}
func (m *AttributeAndId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeAndId.Marshal(b, m, deterministic)
}
func (m *AttributeAndId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeAndId.Merge(m, src)
}
func (m *AttributeAndId) XXX_Size() int {
	return xxx_messageInfo_AttributeAndId.Size(m)
}
func (m *AttributeAndId) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeAndId.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeAndId proto.InternalMessageInfo

func (m *AttributeAndId) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *AttributeAndId) GetAttributeId() []byte {
	if m != nil {
		return m.AttributeId
	}
	return nil
}

type AttributeAndIdList struct {
	AttributeAndIdList   []*AttributeAndId `protobuf:"bytes,1,rep,name=attribute_and_id_list,json=attributeAndIdList,proto3" json:"attribute_and_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AttributeAndIdList) Reset()         { *m = AttributeAndIdList{} }
func (m *AttributeAndIdList) String() string { return proto.CompactTextString(m) }
func (*AttributeAndIdList) ProtoMessage()    {}
func (*AttributeAndIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23ec92774814a82, []int{1}
}

func (m *AttributeAndIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeAndIdList.Unmarshal(m, b)
}
func (m *AttributeAndIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeAndIdList.Marshal(b, m, deterministic)
}
func (m *AttributeAndIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeAndIdList.Merge(m, src)
}
func (m *AttributeAndIdList) XXX_Size() int {
	return xxx_messageInfo_AttributeAndIdList.Size(m)
}
func (m *AttributeAndIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeAndIdList.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeAndIdList proto.InternalMessageInfo

func (m *AttributeAndIdList) GetAttributeAndIdList() []*AttributeAndId {
	if m != nil {
		return m.AttributeAndIdList
	}
	return nil
}

type AttributeList struct {
	Attributes           []*Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AttributeList) Reset()         { *m = AttributeList{} }
func (m *AttributeList) String() string { return proto.CompactTextString(m) }
func (*AttributeList) ProtoMessage()    {}
func (*AttributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e23ec92774814a82, []int{2}
}

func (m *AttributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeList.Unmarshal(m, b)
}
func (m *AttributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeList.Marshal(b, m, deterministic)
}
func (m *AttributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeList.Merge(m, src)
}
func (m *AttributeList) XXX_Size() int {
	return xxx_messageInfo_AttributeList.Size(m)
}
func (m *AttributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeList.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeList proto.InternalMessageInfo

func (m *AttributeList) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*AttributeAndId)(nil), "attrpubapi_v1.AttributeAndId")
	proto.RegisterType((*AttributeAndIdList)(nil), "attrpubapi_v1.AttributeAndIdList")
	proto.RegisterType((*AttributeList)(nil), "attrpubapi_v1.AttributeList")
}

func init() { proto.RegisterFile("List.proto", fileDescriptor_e23ec92774814a82) }

var fileDescriptor_e23ec92774814a82 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x05, 0xc1, 0xe9, 0x56, 0x21, 0x20, 0x14, 0x51, 0xa8, 0xc5, 0x43, 0x4f, 0x01,
	0x57, 0x10, 0xaf, 0xed, 0xad, 0xe0, 0x61, 0xe9, 0x4d, 0x2f, 0x25, 0xdd, 0x74, 0x71, 0x70, 0xb7,
	0x09, 0xed, 0x44, 0xf0, 0x2f, 0xf9, 0x53, 0xfc, 0x55, 0x92, 0xe8, 0xa6, 0x96, 0x65, 0x8f, 0x79,
	0xf3, 0xde, 0xf7, 0x26, 0x03, 0xf0, 0x8c, 0x23, 0x71, 0x3d, 0x28, 0x52, 0x2c, 0x16, 0x44, 0x83,
	0x36, 0xad, 0xd0, 0xd8, 0x7c, 0xdc, 0x5f, 0x5d, 0x14, 0x44, 0x03, 0xb6, 0x86, 0xba, 0xdf, 0x79,
	0xf6, 0x0e, 0xe7, 0x5e, 0x2a, 0x7a, 0x59, 0x49, 0xf6, 0x08, 0x67, 0x62, 0xaf, 0x24, 0x41, 0x1a,
	0xe4, 0xd1, 0x32, 0xe1, 0x33, 0x0a, 0xf7, 0x89, 0x7a, 0xb2, 0xb2, 0x5b, 0x58, 0xf8, 0x47, 0x83,
	0x32, 0x09, 0xd3, 0x20, 0x5f, 0xd4, 0x91, 0xd7, 0x2a, 0x99, 0x6d, 0x80, 0xcd, 0xcb, 0xec, 0xa2,
	0x6c, 0x05, 0x97, 0x53, 0x50, 0xf4, 0xb2, 0x41, 0xd9, 0x6c, 0x71, 0xa4, 0x24, 0x48, 0x4f, 0xf2,
	0x68, 0x79, 0x73, 0xac, 0xdc, 0x11, 0x6a, 0x26, 0x0e, 0x88, 0x59, 0x05, 0xb1, 0x77, 0xb9, 0x8a,
	0x27, 0x00, 0x6f, 0x1b, 0xff, 0xb8, 0xc7, 0x3f, 0xf5, 0xcf, 0x5b, 0x1a, 0xb8, 0x5b, 0xab, 0x1d,
	0xff, 0x54, 0x84, 0x5c, 0x68, 0xe4, 0xeb, 0x2d, 0x76, 0x3d, 0xf1, 0x51, 0x23, 0x1f, 0xba, 0x9d,
	0xda, 0xdf, 0xb1, 0x64, 0xb3, 0xc2, 0x95, 0xd5, 0x5e, 0x63, 0x9b, 0x72, 0x63, 0x0b, 0xfc, 0x0a,
	0xaf, 0x5f, 0x2c, 0xa5, 0x30, 0xf4, 0xc6, 0x9d, 0xa1, 0x34, 0x9b, 0xa9, 0xf5, 0x3b, 0x84, 0xc2,
	0xef, 0xd3, 0x9e, 0xba, 0xd8, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0xde, 0xc6, 0x46,
	0xcb, 0x01, 0x00, 0x00,
}
