name: Unit Tests
on: [push, pull_request_target]

jobs:
  tests:
    name: Tests (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    # always run on push events
    # only run on pull_request_target event when pull request pulls from fork repository
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19, "^1"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: ./sh/gofmt.sh

      - run: go vet ./...

      - run: go test -v -race ./...
